- name: Add Jenkins key and repo
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian binary/
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: latest
    update_cache: yes

- name: Enable and start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
