- name: Install PostgresSQL
  apt:
    name: [postgresql, postgresql-contrib]
    state: present

- name: Install psycopg2 dependencies
  become: yes
  apt:
    name:
      - python3-pip
      - python3-dev
      - libpq-dev
      - build-essential
    state: present
    update_cache: yes

- name: Install psycopg2 Python package
  become: yes
  pip:
    name: psycopg2-binary
    executable: pip3


- name: Create SonarQube DB
  become: yes
  postgresql_db:
    name: sonarqube
    login_user: postgres

- name: Create SonarQube user
  become_user: postgres
  postgresql_user:
    name: "{{ sonar_jdbc_user }}"
    password: "{{ sonar_jdbc_password }}"
    priv: "sonarqube:ALL"

- name: Add sonar user 
  user: 
    name: sonar
    system: yes
    shell: /bin/false

- name: Download SonarQube
  get_url: 
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-25.6.0.109173.zip
    dest: /opt/sonarqube.zip

- name: Unzip and rename
  unarchive:
    src: /opt/sonarqube.zip
    dest: /opt
    remote_src: yes
  notify: restart sonarqube

- name: Template sonar.properties
  template:
    src: sonar.properties.j2
    dest: /opt/sonarqube/conf/sonar.properties
    owner: sonar 
    group: sonar